spring:
  application:
    name: rest
  datasource:
    url: jdbc:postgresql://localhost:5432/student_portal
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver


  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
student:
  portal:
    upload:
      image:
        directory:
          path: /Users/karen/Data/lessons/Java-2025/spring/student-portal-spring/upload_images/


jwt:
  secret: YXNkZmYkIyNzZFNEU0RBQVNERksjQEBkc2ZqZGZrZHNqQEAjZHNmZ2ZnZmdeXiYmWipeJSQkI2RzZHMkIyVzZDQ1MDk5KUkjJCg5V0ZTSUo
  expiration: 600000
server:
  port: 8084
