spring:
  liquibase:
    enabled: true
    change-log: classpath:db/master.xml
  application:
    name: student-portal-spring
  datasource:
    url: jdbc:postgresql://localhost:5432/student_portal
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  mail:
    host: smtp.gmail.com
    port: 587
    username: java2026java@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 10MB
  profiles:
    active:

server:
  port: 8081

student:
  portal:
    upload:
      image:
        directory:
          path: /Users/karen/Data/lessons/Java-2025/spring/student-portal-spring/upload_images/
logging:
  file:
    name: /Users/karen/Data/lessons/Java-2025/spring/student-portal-spring/log/student-portal-spring.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 3

  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    com.example.studentportalspring.controller: DEBUG
